version: 1

before:
  hooks:
    - go mod tidy


builds:
  - id: "conditioner"
    main: "./cmd/"
    binary: "kubectl-conditioner"

    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm

    flags:
      - -trimpath

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: devbytes-cloud
    name: conditioner

dockers:
  - image_templates:
      - "devbytescloud/conditioner:{{ .Tag }}-amd64"
      - "ghcr.io/devbytes-cloud/conditioner:{{ .Tag }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

  - image_templates:
      - "devbytescloud/conditioner:{{ .Tag }}-arm64v8"
      - "ghcr.io/devbytes-cloud/conditioner:{{ .Tag }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

docker_manifests:
  - id: conditioner-docker
    name_template: "devbytescloud/conditioner:{{ .Tag }}"
    image_templates:
      - "devbytescloud/conditioner:{{ .Tag }}-amd64"
      - "devbytescloud/conditioner:{{ .Tag }}-arm64v8"
  - id: conditioner-ghcr
    name_template: "ghcr.io/devbytes-cloud/conditioner:{{ .Tag }}"
    image_templates:
      - "ghcr.io/devbytes-cloud/conditioner:{{ .Tag }}-amd64"
      - "ghcr.io/devbytes-cloud/conditioner:{{ .Tag }}-arm64v8"

brews:
  - name: conditioner

    commit_author:
      name: David Dymko
      email: dymkod@gmail.com

    folder: Formula
    homepage: "https://github.com/devbytes-cloud/conditioner"
    description: "Conditioner plugin allows you to add, update, or remove conditions on Kubernetes nodes"
    license: "Apache-2.0 license"
    install: |
      bin.install "kubectl-conditioner" => "conditioner"

    repository:
      owner: devbytes-cloud
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GORELEASER_AUTH_TOKEN }}"

krews:
  - name: conditioner
    url_template: "https://github.com/devbytes-cloud/conditioner/releases/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Krew plugin update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/devbytes-cloud/conditioner"
    description: "Conditioner allows you to add, update, or remove conditions on Kubernetes nodes. It's a handy tool for cluster administrators to manage node status conditions effectively."
    short_description: "Add, update, or remove conditions on Kubernetes nodes"
    skip_upload: true
